server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/erupt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: yoyor
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
erupt-app:
  # 登录失败几次出现验证码，值为0时表示一直需要登录验证码
  verifyCodeCount: 2
  # 登录密码是否加密传输，特殊场景如：LDAP登录可关闭该功能获取密码明文
  pwdTransferEncrypt: true
erupt:
  # 是否开启csrf防御
  csrfInspect: true
    # 开启redis方式存储session，默认false，开启后需在配置文件中添加redis配置（同 Spring Boot）
    redisSession: false
    # 附件上传存储路径, 默认路径为：/opt/erupt-attachment
    uploadPath: D:/erupt/pictures
    # 是否保留上传文件原始名称
    keepUploadFileName: false
    # 登录session时长（redisSession为true时有效）
    upms.expireTimeByLogin: 60
    # 是否开启任务调度（导入erupt-job时有效）
    job.enable: true
    # 是否记录操作日志，默认true，该功能开启后可在【系统管理 → 操作日志】中查看操作日志
    security.recordOperateLog: true
